### Por questão de consistencia, aqui um Delete para apagar imposters e fazer os exercicios seguidos
DELETE http://localhost:2525/imposters


### Ex0 - Criar Imposter
POST http://localhost:2525/imposters
Content-Type: application/json

{
  "port": 3000,
  "protocol": "http",
  "name": "imposter-inicial"
}

### Ex0 - Validar porta reservada (deve dar erro)
POST http://localhost:2525/imposters
Content-Type: application/json

{
  "port": 3000,
  "protocol": "http",
  "name": "imposter-inicial"
}

### Ex0 - Teste GET (resposta default)
GET http://localhost:3000/qualquercoisa

### Ex1 - Adicionar STUB GET das Marcas de carro
POST http://localhost:2525/imposters/3000/stubs
Content-Type: application/json

{
  "stub": {
    "responses": [
      {
        "is": {
          "statusCode": 200,
          "headers": {
            "Content-Type": "application/json"
          },
          "body": {
            "marcas": ["Toyota", "Audi", "Ford", "Volvo", "Honda"]
          }
        }
      }
    ],
    "predicates": [
      {
        "equals": {
          "method": "GET",
          "path": "/api/marcas"
        }
      }
    ]
  }
}

### Ex1 - Teste GET (resposta customizada)
GET http://localhost:3000/api/marcas


### Ex2 - Stub: pesquisa de carros por marca (GET /api/cars?brand=Toyota)
POST http://localhost:2525/imposters/3000/stubs
Content-Type: application/json

{
  "stub": {
    "responses": [
      {
        "is": {
          "statusCode": 200,
          "headers": {
            "Content-Type": "application/json"
          },
          "body": {
            "brand": "Toyota",
            "results": [{
              "id": 1,
              "modelo": "Prius",
              "preco": "19999€"
            }
            ]
          }
        }
      }
    ],
    "predicates": [
      {
        "equals": {
          "method": "GET",
          "path": "/api/cars",
          "query": { "brand": "Toyota" }
        }
      }
    ]
  }
}

### Ex2 - Teste GET /api/cars?brand=Toyota
GET http://localhost:3000/api/cars?brand=Toyota

### Ex2 - Teste negativo GET /api/cars sem query
GET http://localhost:3000/api/cars

### Ex3 - Stub: GET /api/cars sem parâmetros
POST http://localhost:2525/imposters/3000/stubs
Content-Type: application/json

{
  "stub": {
    "responses": [
      {
        "is": {
          "statusCode": 200,
          "headers": {
            "Content-Type": "application/json"
          },
          "body": {
            "results": []
          }
        }
      }
    ],
    "predicates": [
      {
        "equals": {
          "method": "GET",
          "path": "/api/cars"
        }
      }
    ]
  }
}

### Ex3 - Teste GET /api/cars sem query
GET http://localhost:3000/api/cars

### Ex4 - Stub: login bem-sucedido (POST /api/login com body exacto)
POST http://localhost:2525/imposters/3000/stubs
Content-Type: application/json

{
  "stub": {
    "responses": [
      {
        "is": {
          "statusCode": 200,
          "headers": {
            "Content-Type": "application/json"
          },
          "body": {
            "status": "ok",
            "token": "validtoken"
          }
        }
      }
    ],
    "predicates": [
      {
        "equals": {
          "method": "POST",
          "path": "/api/login",
          "headers": {
            "Content-Type": "application/json"
          }
        } 
      },
      {       
          "deepEquals": {
          "body": {"username":"admin","password":"secret"} 
        }
      }
    ]
  }
}

### Ex4 - Teste POST /api/login (credenciais válidas)
POST http://localhost:3000/api/login
Content-Type: application/json

{"username":"admin","password":"secret"}

### quando o ex 4 é enviado com deepEquals nao devolve nada, quando é enviado com equals devolve
###{
###  "status": "ok",
###  "token": "validtoken"
###}
### entretanto ja percebi o meu erro, tava a fazer deepEquals tanto para os headers quanto para o body, ja funciona corretamente


### Ex5 - Stub: login com credenciais inválidas (POST /api/login genérico)
POST http://localhost:2525/imposters/3000/stubs
Content-Type: application/json

{
  "stub": {
    "responses": [
      {
        "is": {
          "statusCode": 401,
          "headers": {
            "Content-Type": "application/json"
          },
          "body": {
            "error": "invalid_credentials"
          }
        }
      }
    ],
    "predicates": [
      {
        "equals": {
          "method": "POST",
          "path": "/api/login",
          "headers": {
            "Content-Type": "application/json"
          }
        } 
      }
    ]
  }
}

### Ex5 - Teste POST /api/login (credenciais inválidas)
POST http://localhost:3000/api/login
Content-Type: application/json

{"username":"hacker","password":"1234"}

### Ex6 - Stub: criar utilizador (email duplicado) (POST /api/users com email específico)
POST http://localhost:2525/imposters/3000/stubs
Content-Type: application/json

{
  "stub": {
    "responses": [
      {
        "is": {
          "statusCode": 409,
          "headers": {
            "Content-Type": "application/json"
          },
          "body": {
            "error": "email_exists",
            "message": "This email already exists"
          }
        }
      }
    ],
    "predicates": [
      {
        "equals": {
          "method": "POST",
          "path": "/api/users",
          "headers": {
            "Content-Type": "application/json"
          }
        } 
      },
      {
        "contains": {
          "body": 
          "\"email\":\"exists@example.com\""
          
        }
      }
    ]
  }
}

### Ex6 - Teste POST /api/users (email duplicado)
POST http://localhost:3000/api/users
Content-Type: application/json

{"email":"exists@example.com","nome":"Bruno"}


### Ex7 - Stub: criar utilizador com sucesso (POST /api/users)
POST http://localhost:2525/imposters/3000/stubs
Content-Type: application/json

{
  "stub": {
    "responses": [
      {
        "is": {
          "statusCode": 201,
          "headers": {
            "Content-Type": "application/json",
            "Location": "/api/users/1"
          },
          "body": {
            "id": "1",
            "status": "created",
            "message": "este utilizador foi criado com sucesso"
          }
        }
      }
    ],
    "predicates": [
      {
        "equals": {
          "method": "POST",
          "path": "/api/users",
          "headers": {
            "Content-Type": "application/json"
          }
        } 
      }
    ]
  }
}

### Ex7 - Teste POST /api/users (novo email)
POST http://localhost:3000/api/users
Content-Type: application/json

{"nome":"Bruno","email":"novo@example.com","idade":25}

### ex8 - Stub: temperatura — campo obrigatório (POST /api/temperature sem field)
POST http://localhost:2525/imposters/3000/stubs
Content-Type: application/json

{
  "stub": {
    "responses": [
      {
        "is": {
          "statusCode": 400,
          "headers": {
            "Content-Type": "application/json"
          },
          "body": {
            "error": "missing_field",
            "message": "Value é obrigatório"
          }
        }
      }
    ],
    "predicates": [
      {
        "equals": {
          "method": "POST",
          "path": "/api/temperature",
          "headers": {
            "Content-Type": "application/json"
          }
        } 
      },
      {
        "not": {
        "contains": {
         "body": "\"value\""
        }
        }
      }
    ]
  }
}

### Ex8 - Teste POST /api/temperature sem value
POST http://localhost:3000/api/temperature
Content-Type: application/json

{"sensor_id": 1}

### Ex9 - Stub: temperatura — criação com field presente (POST /api/temperature com value)
POST http://localhost:2525/imposters/3000/stubs
Content-Type: application/json

{
  "stub": {
    "responses": [
      {
        "is": {
          "statusCode": 201,
          "headers": {
            "Content-Type": "application/json"
          },
          "body": {
            "status": "Created",
            "message": "Temperatura registada com sucesso"
          }
        }
      }
    ],
    "predicates": [
      {
        "equals": {
          "method": "POST",
          "path": "/api/temperature",
          "headers": {
            "Content-Type": "application/json"
          }
        } 
      },
      {        
        "contains": {
         "body": "\"value\""
        }        
      }
    ]
  }
}

### Ex9 - Teste POST /api/temperature com value
POST http://localhost:3000/api/temperature
Content-Type: application/json

{"sensor_id": 1, "value": 36.5}

### ex10 - Stub: tarefas duplicadas (POST /api/tasks com title "duplicate")
POST http://localhost:2525/imposters/3000/stubs
Content-Type: application/json

{
  "stub": {
    "responses": [
      {
        "is": {
          "statusCode": 409,
          "headers": {
            "Content-Type": "application/json"
          },
          "body": {
            "error": "duplicate_task"
          }
        }
      }
    ],
    "predicates": [
      {
        "equals": {
          "method": "POST",
          "path": "/api/tasks",
          "headers": {
            "Content-Type": "application/json"
          }
        } 
      },
      {        
        "contains": {
         "body": "\"title\":\"duplicate\""
        }        
      }
    ]
  }
}

### Ex10 - Teste POST /api/tasks (titulo duplicado)
POST http://localhost:3000/api/tasks
Content-Type: application/json

{"title":"duplicate"}
