### Ex0 - Criar Imposter
POST http://localhost:2525/imposters
Content-Type: application/json

{
  "port": 3000,
  "protocol": "http",
  "name": "imposter-inicial"
}

### Ex0 - Validar porta reservada (deve dar erro)
POST http://localhost:2525/imposters
Content-Type: application/json

{
  "port": 3000,
  "protocol": "http",
  "name": "imposter-inicial"
}

### Ex0 - Teste GET (resposta default)
GET http://localhost:3000/qualquercoisa

### Ex1 - Adicionar STUB GET das Marcas de carro
POST http://localhost:2525/imposters/3000/stubs
Content-Type: application/json

{
  "stub": {
    "responses": [
      {
        "is": {
          "statusCode": 200,
          "headers": {
            "Content-Type": "application/json"
          },
          "body": {
            "marcas": ["Toyota", "Audi", "Ford", "Volvo", "Honda"]
          }
        }
      }
    ],
    "predicates": [
      {
        "equals": {
          "method": "GET",
          "path": "/api/marcas"
        }
      }
    ]
  }
}

### Ex1 - Teste GET (resposta customizada)
GET http://localhost:3000/api/marcas